"""Optional Ollama export path: Modelfile + merge/GGUF instructions.

Does **not** fine-tune in Ollama. The PEFT adapter (Modal / Hub) remains the
training artifact; this module helps consumers who want a local GGUF.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path

from priceengine.config import AMAZON_LIST_QUESTION, BASE_MODEL, PRICE_PREFIX

logger = logging.getLogger(__name__)

_MODELFILE_TEMPLATE = '''# Generated by priceengine export-ollama
# See docs/OLLAMA.md

FROM ./{gguf_name}

TEMPLATE """{{{{ .Prompt }}}}"""

SYSTEM """You estimate Amazon-style list prices in whole dollars from product text.
When the user prompt ends with "Price is $", continue with NNN.00 only."""

PARAMETER temperature 0.0
PARAMETER num_predict 8
PARAMETER stop "\\n"
'''


def prepare_ollama_export(
    adapter_path: Path,
    *,
    out_dir: Path,
    gguf_name: str = "list-price-qlora.gguf",
    base_model: str = BASE_MODEL,
    copy_modelfile_template: Path | None = None,
) -> dict[str, str]:
    """Stage a Modelfile and write merge/convert instructions.

    Full LoRA merge + llama.cpp conversion are **not** run here (need GPU disk
    and external tools). Returns paths and a shell recipe string.
    """
    adapter_path = adapter_path.expanduser().resolve()
    if not adapter_path.is_dir():
        raise FileNotFoundError(f"Adapter directory not found: {adapter_path}")

    out_dir = out_dir.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if copy_modelfile_template and copy_modelfile_template.is_file():
        shutil.copy(copy_modelfile_template, out_dir / "Modelfile")
    else:
        (out_dir / "Modelfile").write_text(
            _MODELFILE_TEMPLATE.format(gguf_name=gguf_name)
        )

    recipe = f"""# 1) Merge LoRA into the base (needs GPU / enough RAM)
python - <<'PY'
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

base = {base_model!r}
adapter = {str(adapter_path)!r}
out = {str(out_dir / "merged")!r}

tok = AutoTokenizer.from_pretrained(base)
model = AutoModelForCausalLM.from_pretrained(
    base, torch_dtype=torch.float16, device_map="auto"
)
model = PeftModel.from_pretrained(model, adapter)
model = model.merge_and_unload()
model.save_pretrained(out)
tok.save_pretrained(out)
print("Merged →", out)
PY

# 2) Convert with llama.cpp (clone llama.cpp; adjust path)
# python convert_hf_to_gguf.py {out_dir / "merged"} --outfile {out_dir / gguf_name}

# 3) Create the Ollama model
# cd {out_dir} && ollama create list-price -f Modelfile

# Prompt format:
# {AMAZON_LIST_QUESTION}
#
# <title + description>
#
# {PRICE_PREFIX}
"""
    recipe_path = out_dir / "EXPORT_STEPS.sh"
    recipe_path.write_text(recipe)
    logger.info("Wrote %s and Modelfile under %s", recipe_path.name, out_dir)
    return {
        "out_dir": str(out_dir),
        "modelfile": str(out_dir / "Modelfile"),
        "recipe": str(recipe_path),
        "gguf_name": gguf_name,
        "base_model": base_model,
    }
